title: Ashfaque Khowaja
description: >
  Your professional description in 1-2 sentences.
baseurl: ""
url: "https://yourdomain.com"
email: your.email@example.com
github_username: yourusername
twitter_username: yourusername
linkedin_username: yourusername
google_scholar_id: YOUR_ID_HERE
orcid_id: YOUR-ORCID-ID

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# For future compatibility
collections:
  news:
    output: true
    permalink: /:url

# Default front matter
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      published: true