title: Ashfaque Khowaja

baseurl: ""
url: "ashfaquekhowaja.com"
email: khowaja.ashfaqali@hotmail.com
github_url: https://github.com/ashfaquekhowaja
twitter_url: https://x.com/AshfaqueKhowaja
linkedin_username: ashfaquekhowaja/
google_scholar_id: P9J0bO4AAAAJ
orcid_id: 0009-0007-0352-3316

# Build settings
theme: minima
plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter

# Optional
defaults:
  - scope:
      path: ""
    values:
      layout: default
