title: Ashfaque Khowaja
description: >
  Your professional description in 1-2 sentences.
baseurl: ""
url: "ashfaquekhowaja.com"
email: your.email@example.com
github_username: yourusername
twitter_username: yourusername
linkedin_username: yourusername
google_scholar_id: YOUR_ID_HERE
orcid_id: YOUR-ORCID-ID

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# For future compatibility
collections:
  news:
    output: true
    permalink: /:url

# Default front matter
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      published: true

permalink: pretty

include:
  - .webp
  - .jpg
  - .png

# Sass configuration to suppress deprecation warnings
sass:
  quiet_deps: true
  style: compressed
  sourcemap: never
  load_paths:
    - _sass
  sass_dir: _sass